repos:
- repo: local
  hooks:
    - id: flake8
      name: flake8
      entry: git status -s -uno | grep -v '^ '| awk '{print $2}' | xargs flake8 --config .flake8
      language: system
      types: [python]
      pass_filenames: false
