[mgr]
cwd = {fg = "#9ee8aa"}

[tabs]
active = {fg = "#fcfafa", bg = "#cc0606" }
inactive = {fg = "#fcfafa", bg = "#1613a1"}

[status]
# https://yazi-rs.github.io/docs/configuration/theme#status
overall = {fg = "#fcfafa", bg = "#1c2f54"}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }
perm_type = {fg = "#ffffff"}
perm_read = {fg = "#3bfc38"}
perm_write = {fg = "#ffb078"}
perm_exec = {fg = "#fbff00"}
perm_sep = {fg = "#ffffff"}

[mode]
# https://yazi-rs.github.io/docs/configuration/theme#mode
normal_main = { fg = "#ffffff", bg = "#163b87" }
normal_alt = { fg = "#ffffff", bg = "#6b184f" }

select_main = { fg = "#ffffff", bg = "#0f664c" }
select_alt = { fg = "#ffffff", bg = "#6b184f" }

unset_main = { fg = "#000000", bg = "#c4c4c4", bold = true }
unset_alt = { fg = "#ffe3e6", bg = "#a32231"}
