[mgr]
ratio = [1, 2, 4]

[opener]
play = [
    	{ run = '/home/stepan/git_repos/kn7072/BASH/celluloid_size.bash "$@"', orphan = true, for = "linux", desc = "play to celluloid" },
	{ run = '/home/stepan/git_repos/kn7072/BASH/vlc_size.bash "$@"', orphan = true, for = "linux", desc = "play to vlc" },

]
xviewer = [
    { run = 'xviewer "$@"', orphan = true, for = "unix" },
]

# Редакторы
ksnip = [
    { run = 'ksnip "$@"', orphan = true, for = "unix" },
]
inkscape = [
    { run = 'inkscape "$@"', orphan = true, for = "unix" },
]
# Читалки для книг
pdf = [
    { run = 'sioyek "$@"', orphan = true, desc = "Sioyek" },
    { run = 'okular "$@"', orphan = true, desc = "Okular" }
]
# Okular хорошо читает DjVu и EPUB
book = [
    { run = 'okular "$@"', orphan = true, desc = "Okular" },
    { run = 'xdg-open "$@"', desc = "Системное приложение" }
]

[preview]
# Maximum preview width and height for images.
max_width = 2560
max_height = 1920

# name: Glob expression for matching the file name. Case-insensitive by default, add \s to the beginning to make it sensitive.
# mime: Glob expression for matching the mime-type. Case-insensitive by default, add \s to the beginning to make it sensitive.
# use: Opener name corresponding to the names in the [opener] section.

# если использовать такой стиль https://yazi-rs.github.io/docs/configuration/yazi#open
# тогда при вызове интерактивоного режима (O) помимо проигрывателя будут доступны другие опции
[open]
prepend_rules = [
    # Правила для читалок книг(ставим первым для приоритета)
    { mime = "application/pdf", use = ["pdf"] },
    { name = "*.pdf", use = ["pdf"] },
    { name = "*.djvu", use = ["book"] },
    { name = "*.epub", use = ["book"] },
    { name = "*.cbr", use = ["book"] },
    { name = "*.cbz", use = ["book"] },

	# Правила для видео
	{ name = "*.mp4", use = [ "play" ] },
	{ name = "*.mkv", use = [ "play" ] },
	{ name = "*.avi", use = [ "play" ] },
	{ name = "*.wmv", use = [ "play" ] },
	{ name = "*.ts", use = [ "play" ] },

    # ПРАВИЛО ДЛЯ КАРТИНОК (ставим первым, чтобы оно имело приоритет)
    { mime = "image/*", use = [ "xviewer" ] },

]
# https://github.com/boydaihungst/mediainfo.yazi
[plugin]
  prepend_preloaders = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
  ]
  prepend_previewers = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
  ]

