#!/bin/bash

# Логирование
# exec >~/.bspwm.log 2>&1

pgrep -x sxhkd >/dev/null || sxhkd &

# расставляем мониторы на нужные места
"$HOME/.xprofile"

HDMI_MONITOR="HDMI-1"
VGA_MONITOR=$(xrandr -q | grep -Ei "VGA.* connected" | awk '{print $1}')

# bspc monitor "$VGA_MONITOR" -d 1 2 3

# если нужно разделить рабочие столы по мониторам - работает не так как ожидается,
# все цифры рабочих столов отображаются на обоих мониторах
if [[ -n ${VGA_MONITOR} ]]; then
  # порядок "$VGA_MONITOR" "$HDMI_MONITOR" имеет значение - первым должен идти основной монитор
  bspc wm -O "$VGA_MONITOR" "$HDMI_MONITOR"
  bspc monitor "$VGA_MONITOR" -d 1 2 3 [x]
  bspc monitor "$HDMI_MONITOR" -d 1
else
  bspc monitor "$HDMI_MONITOR" -d 1 2 3 [x]
fi

bspc config border_width 4
bspc config window_gap 2

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a Nemo desktop='^2' follow=on state=floating

bspc rule -a Io.github.celluloid_player.Celluloid state=floating manage=on layer=normal follow=on # rectangle=1248x790+2233+160
bspc rule -a vlc state=floating manage=on layer=normal follow=on rectangle=1500x900+2000+100

bspc config normal_border_color "#111111" # простая рамка
# Color of the border of a focused window of an unfocused monitor.
bspc config active_border_color "#e5a50a"
# Color of the border of a focused window of a focused monitor.
bspc config focused_border_color "#ff5f00" # рамка в фокусе

# Переключение раскладок клавиатуры
setxkbmap -layout us,ru -option grp:alt_shift_toggle

"$HOME/.config/polybar/launch.sh"
