-- Basic
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')

-- Plugins
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require("plugins.mason")
require("plugins.cmp")
require("plugins.telescope")
require("plugins.nullls")
require("plugins.hop")
require("plugins.toggleterm")
require("plugins.buffline")
require("plugins.dashboard")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.whichkey")
require("plugins.autopairs")
require("plugins.comments")
require("plugins.nvimdapgo")
require("plugins.nvimdap")
require("plugins.nvimdapc")
require("plugins.nvimdapui")
-- require("plugins.nvim-whid")
require("plugins.masonnvimdap")
require("plugins.luadebugger")
-- require("plugins.testdebug")
require("plugins.lsp_config")
-- vim.opt.runtimepath:prepend("~/example-plugin")
require("plugins.test")
require("plugins.ctags")
require("plugins.nvim_window")
require("plugins.switchbuffer")
require("plugins.study_nvim")
require("plugins.vimvsnip")
require("plugins.nvim_surround")
