- name: create user
  hosts: group3
  become: yes

  tasks:

  - name: create groups
    group:
        name: "{{item}}"
        state: present
    loop:
        - dev
        - test

    #- name: Create user
    #  user:
    #     name: test1
    #     shell: /bin/bash
    #     append: yes
    #     groups: dev,test
    #     home: /home/test1


  - name: Create user
    user:
        name: "{{item.clientname}}"
        shell: /bin/bash
        append: yes
        groups: dev,test
        home: "/home/{{item.homedir}}"
    with_items:
             - {clientname: client1, homedir: client1}
             - {clientname: client2, homedir: client2}
 
