#!/bin/bash

report_disk_space () {
cat <<- _EOF_
<h2>Disk Space Utilization</h2>
<pre>$(df -h)</pre>
_EOF_
return
}


report_disk_space 

x=5

if [[ $x = 5 ]]; then
    echo "x equals 5"
else
    echo "x does not equal 5"
fi    

ANSWER=maybe
if [ -z "$ANSWER" ]; then
  echo "There is no answer." >&2
exit 1
fi

if [ "$ANSWER" == "yes" ]; then
  echo "The answer is YES."
elif [ "$ANSWER" == "no" ]; then
  echo "The answer is NO."
elif [ "$ANSWER" == "maybe" ]; then
  echo "The answer is MAYBE."
else
  echo "The answer is UNKNOWN."
fi
