# coding: utf8

import mysql
import mysql.connector as con
from mysql.connector import Error

ssh_host = 'remtvstudio.myjino.ru'
ssh_login = 'remtvstudio'
ssh_password = 'testpassword2014'


host = '127.0.0.1'
database = 'remtvstudio_test'
user = '045333190_test'  # remtvstudio
password = 'testpassword2015'  # testpassword2014


def connect(host, database, user, password):
    """ Connect to MySQL database """
    try:
        conn = mysql.connector.connect(host=host,
                                       database=database,
                                       user=user,
                                       password=password)
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM user_name")
        row = cursor.fetchone()  # Метод fetchone() возвращает следующую строку набора результатов запроса или None
                                 #  в случае, если строк не осталось
        while row is not None:
            print(row)
            row = cursor.fetchone()

        if conn.is_connected():
            print('Connected to MySQL database')
    except Error as e:
        print(e)
    finally:
        cursor.close()
        conn.close()

def insert_book(*args):  # title, isbn
    query = "INSERT INTO user_name(s_name, f_name) " \
            "VALUES(%s,%s)"
    create_table = 'CREATE TABLE drivers'\
                   '    (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,'\
                   '     title VARCHAR(255) NOT NULL,'\
                   '     meta_d VARCHAR(255) NOT NULL,'\
                   '     meta_k VARCHAR(255) NOT NULL,'\
                   '     text BLOB NOT NULL'\
                   '     )'
    query_insert = 'INSERT INTO drivers(title, meta_d, meta_k, text)'\
                   'VALUES(%s,%s,%s,%s)'
    #args = (title, isbn)
    try:
        conn = mysql.connector.connect(host=host, database=database, user=user, password=password)
        cursor = conn.cursor()
        cursor.execute(query_insert, args) #create_table, args)

        if cursor.lastrowid:  # В случае, если новая строка была вставлена успешно, мы можем получить последний
                              #  вставленный id столбца АUTO INCREMENT с помощью свойство lastrowid
            print('last insert id', cursor.lastrowid)
        else:
            print('last insert id not found')
        conn.commit()  # утвердить изменения
    except Error as error:
        print(error)
    finally:
        cursor.close()
        conn.close()
#obj = con.connect(host='localhost', port=3306, database=database, user='045333190_test', password=password)  # , charset = "win1252"
#connect(host='localhost', database=database, user='045333190_test', password=password)
text = """<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">BIOS</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell Studio 1557 System BIOS, A09</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A09</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">03 ноя 2011</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">2595800</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R301433.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">BIOS</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell Studio 1557 System BIOS, A05</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A05</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">03 ноя 2011</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">1379458</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">HKC_DOS_A05.zip</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">SATA</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Intel Rapid Storage Technology Driver</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A02</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">20 дек 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">11143064</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R263958.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">SATA</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Seagate ST9160412AS/ST9250410AS/ST9320423AS/ST9500420AS Firmware Update</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A00</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">05 мар 2014</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">4669544</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R250679.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">SATA</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Seagate ST9500420ASG/ST9160412ASG/ST9250410ASG/ST9320423ASG/ST980412ASG Firmware Update</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A00</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">05 мар 2014</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">4669872</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R250352.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Видео</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">AMD ATI Mobility Radeon™ HD 3650, ATI Mobility Radeon™ HD 3450, ATI Mobility Radeon™ HD 3650, ATI Mobility Radeon™ HD 3450, ATI Mobility Radeon™ HD 3670, ATI Mobility Radeon™ HD 4570, ATI Mobility Radeon™ HD 565v, ATI Mobility Radeon™ HD 4670, ATI Mobility Radeon™ HD 4330, ATI Mobility Radeon™ HD 5450, ATI Mobility Radeon™ HD 5650, ATI Mobility Radeon HD 5470 / HD4200, ATI Mobility Radeon™ HD 5730, ATI Mobility Radeon™ HD 550v, ATI Mobility Radeon™ HD 540v, ATI Mobility Radeon™ HD 545v, v.8.742.0.0000, A23</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A23</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">03 ноя 2011</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">136808608</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R276519.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Диагностика</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell 32 Bit Diagnostics (Graphical User Interface version), v.A1367A0 / A0482, A1367A0</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A1367A0</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">03 ноя 2011</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">4193984</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">CW1367A0.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Драйверы для развертывания ОС</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell IN2020M Monitor Driver</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A00-00</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">20 дек 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">129176</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">DELL_IN2020MF-MONITOR_A00-00_R269753.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Драйверы для развертывания ОС</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell ST2220C Monitor Driver</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A00-00</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">21 мар 2014</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">127696</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">DELL_ST2220C-MONITOR_A00-00_R271165.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Звук</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">IDT 92HD73C1 Audio, v.6.10.0.6267, A18</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A18</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">07 июл 2012</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">16874568</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R261324.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Модем/cвязь</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell Wireless 5620 EVDO-HSPA Mobile Broadband Mini-Card, v.1.1.100, A08</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A08</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">13 апр 2012</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">30145616</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">DELL_WIRELESS-5620-EVDO-HSPA_A08_R257882.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Модем/cвязь</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell Wireless 5540 HSPA Mini Card Driver</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A06</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">08 янв 2014</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">38898640</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R251268.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Модем/cвязь</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Conexant D400 External USB 56K Modem Driver</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A00</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">21 мар 2014</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">2007568</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">Conexant_D400-External-USB-5_A00_R223361.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Модем/cвязь</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Conexant D400 External USB 56K Modem Utility</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A00</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">21 мар 2014</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">4181176</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">CONEXANT_D400-USB-MODEM_DPP14_A00_SETUP_ZPE.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Мышь, клавиатура и устройства ввода</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Logitech Bluetooth Travel Mouse Application</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A02-00</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">13 дек 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">144109622</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R241392.zip</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Мышь, клавиатура и устройства ввода</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell Touchpad Driver</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A07</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">20 дек 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">31474264</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R242713.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Набор микросхем</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Ricoh CardReader R5U230, v.2.03.02.02, A00</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A00</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">03 ноя 2011</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">4385469</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R227189.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Приложение</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell QuickSet Application</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A07</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">20 дек 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">5591816</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">Dell_QuickSet_A07_R272666.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Приложение</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell DataSafe Local Patch/Upgrade</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A00</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">05 мар 2014</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">457112</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">DELL_DATASAFE-LOCAL-2-0_A00_R260476.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Приложение</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell Mobile Broadband Manager Application</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A03</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">18 дек 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">31075088</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">DELL_MOBILE-BROADBAND-MANAGE_A03_R251265.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Приложение</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Sonic Solutions Roxio Burn Application</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A00</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">13 дек 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">19729279</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R244364_RoxioBurn_v1.01_120B16F.zip</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Сети</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell Wireless WLAN 1501 Half Mini-Card Driver</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A01</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">18 дек 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">83806424</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R258276.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Сети</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Intel Intel(R) WiFi Link 5300, Intel(R) WiFi Link 5100, v.tic TRWFW0986D , A01</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A01</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">03 ноя 2011</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">26032432</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R246753.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Сети</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell Wireless WLAN 1397/1510 Half Mini Card Application</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A01</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">21 мар 2014</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">77519000</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R228532.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Сети</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell Wireless 365 Bluetooth Module Application</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A03-1</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">19 дек 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">65174592</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R235168.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Сети</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell Wireless WLAN 1520 Half MiniCard Driver</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A01</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">18 дек 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">77518768</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R228550.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Сети</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Realtek RTL8211CL Ethernet Controller, RTL8111DL Ethernet Controller, v.7.003.0522.2009, A00</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A00</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">07 июл 2012</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">5931244</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R227190.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Системные утилиты</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Dell System Software Utility</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A01</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">21 мар 2014</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">16942792</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">DSS_UTIL_WIN_R260746.EXE</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Системные утилиты</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">ST Microelectronics DE351DL Motion Sensor, v.1.08.1.0, A02</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A02</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">07 июл 2012</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">5194760</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R230426.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Съемные накопители</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">TSST TS-T633C 12.7mm Slotload 8x DVDRW, v.D900, A08</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A08</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">03 ноя 2011</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">2672272</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R306353.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Съемные накопители</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">HLDS CA 10N 12.7mm SATA Slotload 4X BD-Combo Firmware Update</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A05</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">05 июн 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">2753386</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">CA10N-WIN7-A108-normal.zip</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Съемные накопители</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">HLDS GA11N 12.7mm SATA Slotload 8X DVDRW Firmware Update</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A01</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">05 июн 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">2499446</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">GA11N-A101.zip</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Съемные накопители</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Optiarc AD-7640S 12.7mm SATA Slotload 8X DVDRW Firmware Update</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A03</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">05 июн 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">1564161</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">AD-7640S HD18.zip</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Съемные накопители</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Optiarc BC-5600S 12.7mm SATA Slotload BD-Combo Firmware Update</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A03</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">05 июн 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">1954306</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">BC5600S_V10AB.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Съемные накопители</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Panasonic UJ235A SATA 4X BD-RE Firmware Update</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A01</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">05 июн 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">1322368</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">PANASONIC_UJ235A-12-7MM-SATA_A01_R227099.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">Съемные накопители</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">TSST TS-T633A 12.7mm Slotload 8x DVDRW Firmware Update</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A06</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">05 июн 2013</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">1791864</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R225697.exe</span></div>################ NEW DRIVER ################
<h1>Скачать драйверы studio-1557 [W764]</h1><div class="driver_block_header">ЦП</div><div class="driver_block_description">    <span class="driver_block_description_td">Название</span><span class="driver_block_description_name">Intel Turbo Boost Technology Monitor Software, v.1.0.186.6, A01</span><span class="driver_block_download_link"><a href="">Скачать</a></span>    <span class="driver_block_description_td">Версия: </span><span class="driver_block_description_version">A01</span>    <span class="driver_block_description_td">Дата выпуска: </span><span class="driver_block_description_date">03 ноя 2011</span>    <span class="driver_block_description_td">Размер (Мб): </span><span class="driver_block_description_size">18296720</span>    <span class="driver_block_description_td">Имя файла: </span><span class="driver_block_description_file_name">R258794.exe</span></div>################ NEW DRIVER ################
"""
insert_book('stepan','ivan', 'anton', text)
print()