path:
  dir_all_word_files: /home/stapan/GIT/kn7072/ANKI/WORDS
  words_for_learn: /home/stapan/GIT/kn7072/ANKI/TelegramBot/WORDS_FOR_LEARN.txt
  words_for_learn_clean: /home/stapan/GIT/kn7072/ANKI/TelegramBot/WORDS_FOR_LEARN_CLEAN.txt