path:
  dir_all_word_files: /home/stapan/GIT/kn7072/ANKI/WORDS
  words_for_learn: /home/stapan/GIT/kn7072/ANKI/TelegramBot/WORDS_FOR_LEARN.txt
  words_for_learn_clean: /home/stapan/GIT/kn7072/ANKI/TelegramBot/WORDS_FOR_LEARN_CLEAN.txt
  sentence_to_learn: /home/stapan/GIT/kn7072/ANKI/TelegramBot/SENTENCE_TO_LEAR.txt
  new_file_with_sentence_and_words: /home/stapan/GIT/kn7072/ANKI/TelegramBot/SENTENCE_TO_COMMIT.txt