path:
  dir_all_word_files: /home/stepan/GIT/kn7072/ANKI/WORDS
  words_for_learn: /home/stepan/GIT/kn7072/ANKI/TelegramBot/WORDS_FOR_LEARN.txt
  words_for_learn_clean: /home/stepan/GIT/kn7072/ANKI/TelegramBot/WORDS_FOR_LEARN_CLEAN.txt
  sentence_to_learn: /home/stepan/GIT/kn7072/ANKI/TelegramBot/SENTENCE_TO_LEAR.txt
  new_file_with_sentence_and_words: /home/stepan/GIT/kn7072/ANKI/TelegramBot/SENTENCE_TO_COMMIT.txt
  path_to_sentence: /home/stepan/GIT/kn7072/ANKI/Предложения.txt
  file_to_add_sentence: ./ADD_SENTENCE.txt
  count_sentence_for_word: 3